- client/src/app/components/events/event-feed/event-feed.component.html
- client/src/app/components/events/event-feed/event-feed.component.ts
- client/src/app/components/events/event-feed/event-feed.gql
- client/src/app/components/events/event-timeline-item/event-timeline-item-module.ts
- client/src/app/components/events/event-timeline-item/event-timeline-item.component.html
- client/src/app/components/shared/site-stats-card/site-stats-card.component.html
- client/src/app/components/shared/site-stats-card/site-stats-card.component.less
- client/src/app/components/shared/site-stats-card/site-stats-card.module.ts
- client/src/app/components/variant-groups/variant-group-tag/variant-group-tag.component.less
- client/src/app/generated/civic.apollo.ts
- client/src/app/generated/server.model.graphql
- client/src/app/generated/server.schema.json
- client/src/app/views/welcome/welcome.component.html
- client/src/app/views/welcome/welcome.component.less
- client/src/app/views/welcome/welcome.component.ts
- client/src/app/views/welcome/welcome.module.ts
- server/app/graphql/resolvers/top_level_events.rb
- server/app/graphql/types/connections/events_connection.rb
> display icons and event feed on homepage

- client/src/app/views/variants/variants-detail/variants-summary/variants-summary.page.html
- server/app/graphql/types/entities/variant_type.rb
> Fix 3' and 5' coordinate display

- client/src/app/components/shared/tag-overflow/tag-overflow.component.less
- client/src/app/components/sources/sources-table/sources-table.component.html
- client/src/app/components/sources/sources-table/sources-table.module.ts
> Create a new plain-tag-overflow component and use it for the author list on the sources table

- server/app/graphql/resolvers/browse_genes.rb
- server/app/graphql/resolvers/browse_variants.rb
> make table filtering a substring match when using a json function

- server/app/graphql/types/browse_tables/browse_source_type.rb
- server/db/migrate/20220331153354_update_source_browse_table_rows_to_version_3.rb
- server/db/schema.rb
- server/db/views/source_browse_table_rows_v03.sql
> distinct author list when generating sql view. closes #299

- client/src/app/components/genes/genes-table/genes-table.component.html
- client/src/app/components/genes/genes-table/genes-table.module.ts
- client/src/app/components/organizations/organizations-table/organizations-table.component.html
- client/src/app/components/organizations/organizations-table/organizations-table.module.ts
- client/src/app/components/variants/variants-table/variants-table.component.html
- client/src/app/components/variants/variants-table/variants-table.module.ts
- client/src/app/core/pipes/pipes.module.ts
- client/src/app/core/pipes/pluck-pipe.ts
- server/app/graphql/resolvers/top_level_organizations.rb
> make aliases on gene and variant browse tables into tags

- client/src/app/components/assertions/assertions-table/assertions-table.component.html
- client/src/app/components/clinical-trials/clinical-trials-table/clinical-trials-table.component.html
- client/src/app/components/clinical-trials/clinical-trials-table/clinical-trials-table.module.ts
- client/src/app/components/diseases/diseases-table/diseases-table.component.html
- client/src/app/components/diseases/diseases-table/diseases-table.module.ts
- client/src/app/components/drugs/drugs-table/drugs-table.component.html
- client/src/app/components/drugs/drugs-table/drugs-table.module.ts
- client/src/app/components/genes/genes-table/genes-table.component.html
- client/src/app/components/genes/genes-table/genes-table.module.ts
- client/src/app/components/organizations/organizations-table/organizations-table.component.html
- client/src/app/components/organizations/organizations-table/organizations-table.component.ts
- client/src/app/components/organizations/organizations-table/organizations-table.module.ts
- client/src/app/components/phenotypes/phenotypes-table/phenotypes-table.component.html
- client/src/app/components/phenotypes/phenotypes-table/phenotypes-table.module.ts
- client/src/app/components/source-suggestions/source-suggestions-table/source-suggestions-table.component.html
- client/src/app/components/sources/sources-table/sources-table.component.html
- client/src/app/components/sources/sources-table/sources-table.module.ts
- client/src/app/components/variant-groups/variant-groups-table/variant-groups-table.component.html
- client/src/app/components/variant-types/variant-types-table/variant-types-table.component.html
- client/src/app/components/variant-types/variant-types-table/variant-types-table.module.ts
- client/src/app/components/variants/variants-table/variants-table.component.html
- client/src/app/components/variants/variants-table/variants-table.module.ts
> Add Load More button to all tables and apply consistent styling

- client/src/app/views/assertions/assertions-home/assertions-home.module.ts
- client/src/app/views/assertions/assertions-home/assertions-home.page.html
- client/src/app/views/assertions/assertions-home/assertions-home.page.ts
> Add assertion home section navigation

- client/src/app/layout/layout.component.html
- client/src/app/views/curation/curation-activity/curation-activity-routing.module.ts
- client/src/app/views/curation/curation-activity/curation-activity.module.ts
- client/src/app/views/curation/curation-activity/curation-activity.view.html
- client/src/app/views/curation/curation-activity/curation-activity.view.less
- client/src/app/views/curation/curation-activity/curation-activity.view.ts
- client/src/app/views/curation/curation-activity/curation-timeline/curation-timeline.module.ts
- client/src/app/views/curation/curation-activity/curation-timeline/curation-timeline.page.html
- client/src/app/views/curation/curation-activity/curation-timeline/curation-timeline.page.ts
- client/src/app/views/curation/curation-queues/curation-queues-routing.module.ts
- client/src/app/views/curation/curation-queues/curation-queues.module.ts
- client/src/app/views/curation/curation-queues/curation-queues.view.html
- client/src/app/views/curation/curation-queues/curation-queues.view.ts
- client/src/app/views/curation/curation-routing.module.ts
- client/src/app/views/curation/curation.module.ts
Implements a Curation section w/ Queues and Activity views.
> curation section Queues and Activity views/pages

- client/src/app/forms/assertion-revise/assertion-revise.form.ts
- client/src/app/forms/assertion-submit/assertion-submit.form.ts
- client/src/app/forms/config/types/fda-approval-checkbox/fda-approval-checkbox.type.ts
- client/src/app/forms/config/types/fda-test-checkbox/fda-test-checkbox.type.ts
- server/app/graphql/mutations/submit_assertion.rb
This is the last tweak to the assertion form that closes #343
> various tweaks to assertion form validation state

- client/src/app/components/layout/viewer-button/viewer-button.component.html
- client/src/app/components/layout/viewer-button/viewer-button.component.less
- client/src/app/components/layout/viewer-button/viewer-button.module.ts
- client/src/app/components/users/user-avatar/user-avatar.component.html
- client/src/app/components/users/user-avatar/user-avatar.component.ts
Updated layout, styles for various layout header controls
> header viewer button, notifications, add entity button refactor

- client/src/app/components/assertions/assertions-table/assertions-table.component.html
- client/src/app/components/assertions/assertions-table/assertions-table.query.gql
- client/src/app/generated/civic.apollo.ts
- client/src/app/generated/server.field-policies.ts
- client/src/app/generated/server.model.graphql
- client/src/app/generated/server.schema.json
- server/app/graphql/resolvers/browse_variants.rb
- server/app/graphql/resolvers/top_level_assertions.rb
- server/app/graphql/resolvers/top_level_evidence_items.rb
- server/app/graphql/types/browse_tables/assertion_sort_columns.rb
- server/app/graphql/types/entities/assertion_type.rb
- server/app/models/actions/accept_revisions.rb
- server/app/models/actions/submit_assertion.rb
- server/app/models/assertion.rb
- server/app/models/concerns/moderated.rb
- server/db/migrate/20220407144259_add_eid_count_to_assertions.rb
- server/db/schema.rb
Closes #388 
Closes #390
Closes #336
> Update various table default sorts

- client/src/app/components/users/user-card/user-card.component.html
- client/src/app/components/users/user-card/user-card.module.ts
- client/src/app/components/users/user-tag/user-tag.component.html
- client/src/app/components/users/user-tag/user-tag.component.ts
- client/src/app/generated/civic.apollo.ts
- client/src/app/views/organizations/organizations-members/organizations-members.query.gql
> Improve user cards

- client/src/app/forms/assertion-revise/assertion-revise.form.html
- client/src/app/forms/assertion-submit/assertion-submit.form.html
- client/src/app/forms/evidence-submit/evidence-submit.form.html
> Comment out form model debug json

- client/src/app/components/source-suggestions/source-suggestions-table/source-suggestions-table.component.html
> Display source suggestion comment on a tooltip

- client/src/app/graphql/graphql.type-policies.ts
> Add clinicalTrialId filter to evidenceItems type policy

- server/app/graphql/types/queries/data_release_query.rb
TSV paths include the release date in their filename.
> Correct links on data releases pages

- client/src/app/components/flags/flaggable/flaggable.module.ts
> Fix nonworking flag ribbon link

- client/src/app/components/events/event-feed/event-feed.component.ts
- client/src/app/components/layout/viewer-button/viewer-button.component.ts
- client/src/app/components/source-suggestions/source-suggestions-table/source-suggestions-table.component.html
> refresh notifications and event feeds automatically in production mode

- client/src/app/components/layout/viewer-button/viewer-button.component.html
> Hide notification count badge when count is zero

- server/app/graphql/mutations/reject_revisions.rb
> Ensure that ready? on RejectRevision returns true at the end

- client/src/app/components/source-suggestions/source-suggestions-table/source-suggestions-table.component.html
- client/src/app/components/source-suggestions/source-suggestions-table/source-suggestions-table.module.ts
- client/src/app/forms/evidence-submit/evidence-submit.form.html
- client/src/app/forms/evidence-submit/evidence-submit.form.ts
- client/src/app/forms/evidence-submit/evidence-submit.query.gql
- client/src/app/generated/civic.apollo.ts
- client/src/app/generated/server.field-policies.ts
- client/src/app/generated/server.model.graphql
- client/src/app/generated/server.schema.json
- server/app/graphql/resolvers/browse_source_suggestions.rb
- server/app/graphql/types/queries/source_queries.rb
- server/app/graphql/types/source_suggestion_values_type.rb
> Allow curating an EID from a source suggestion

- client/src/app/core/pipes/color-name-for-status-pipe.ts
> Color accepted evidence/assertion tags green

- client/src/app/views/variants/variants-detail/variants-summary/variants-summary.page.html
> Fix myvariantinfo empty prompt

- client/src/app/components/assertions/assertions-table/assertions-table.component.html
- client/src/app/components/clinical-trials/clinical-trials-table/clinical-trials-table.component.html
- client/src/app/components/diseases/diseases-table/diseases-table.component.html
- client/src/app/components/drugs/drugs-table/drugs-table.component.html
- client/src/app/components/evidence/evidence-table/evidence-table.component.html
- client/src/app/components/genes/genes-table/genes-table.component.html
- client/src/app/components/phenotypes/phenotypes-table/phenotypes-table.component.html
- client/src/app/components/sources/sources-table/sources-table.component.html
- client/src/app/components/variant-groups/variant-groups-table/variant-groups-table.component.html
- client/src/app/components/variant-types/variant-types-table/variant-types-table.component.html
- client/src/app/components/variants/variants-table/variants-table.component.html
- server/app/graphql/resolvers/browse_diseases.rb
> For count table columns, change the default order in which the sorting is executed

- client/src/app/components/revisions/revision-list/revision-list.component.ts
- client/src/app/components/revisions/revisions-list-and-filter/revisions-list-and-filter.component.html
- client/src/app/components/revisions/revisions-list-and-filter/revisions-list-and-filter.component.ts
- client/src/app/core/pipes/icon-name-for-subscribable-entity.ts
- client/src/app/core/utilities/mutation-state-wrapper.ts
- client/src/app/forms/assertion-submit/assertion-submit.form.ts
- client/src/app/forms/config/types/disease-input/disease-input.type.ts
- client/src/app/forms/config/types/drug-input/drug-input.type.ts
- client/src/app/forms/config/types/variant-input/variant-input.type.ts
- client/src/app/forms/evidence-submit/evidence-submit.form.ts
- client/src/app/forms/source-submit/source-submit.form.ts
- client/src/app/forms/variant-group-submit/variant-group-submit.form.ts
> Update open revisions counter after revision acceptance/rejection

- server/app/models/my_variant_info.rb
> Include updated_at timestamp when calculating cache key for variants

- client/src/app/components/flags/flag-popover/flag-popover.component.html
- client/src/app/components/flags/flag-popover/flag-popover.component.less
- client/src/app/components/flags/flag-popover/flag-popover.component.ts
- client/src/app/components/flags/flag-popover/flag-popover.module.ts
- client/src/app/components/flags/flag-popover/flag-popover.query.gql
- client/src/app/components/flags/flag-tag/flag-tag.component.html
- client/src/app/components/flags/flag-tag/flag-tag.component.ts
- client/src/app/components/flags/flag-tag/flag-tag.module.ts
- client/src/app/components/revisions/revision-popover/revision-popover.component.html
- client/src/app/components/revisions/revision-popover/revision-popover.component.less
- client/src/app/components/revisions/revision-popover/revision-popover.component.ts
- client/src/app/components/revisions/revision-popover/revision-popover.module.ts
- client/src/app/components/revisions/revision-popover/revision-popover.query.gql
- client/src/app/components/revisions/revision-tag/revision-tag.component.html
- client/src/app/components/revisions/revision-tag/revision-tag.module.ts
- client/src/app/generated/civic.apollo.ts
- server/app/models/flag.rb
> New popovers for flags and revisions

- client/src/app/components/revisions/revision-list-diff/revision-list-diff.component.html
- client/src/app/components/revisions/revision-list-diff/revision-list-diff.module.ts
- client/src/app/components/revisions/revisions-list-and-filter/revisions-list-and-filter.query.gql
- client/src/app/core/pipes/camel-case-to-words-pipe.ts
- client/src/app/core/pipes/pipes.module.ts
- client/src/app/generated/civic.apollo.ts
- client/src/app/generated/server.field-policies.ts
- client/src/app/generated/server.model.graphql
- client/src/app/generated/server.schema.json
- server/app/graphql/types/revisions/linkout_data.rb
- server/app/graphql/types/revisions/moderated_field_type.rb
> Gracefully display revisions that point to deleted entities

- client/src/app/forms/config/types/source-input/source-selector/source-selector-typeahead/source-selector-typeahead.type.html
- client/src/app/forms/config/types/source-input/source-selector/source-selector-typeahead/source-selector-typeahead.type.ts
> when there is no source citation, fall back on the name

- client/src/app/components/assertions/assertions-popover/assertion-popover.component.html
- client/src/app/components/assertions/assertions-popover/assertion-popover.query.gql
- client/src/app/components/assertions/assertions-popover/assertions-popover.module.ts
- client/src/app/components/drugs/cvc-drug-popover/cvc-drug-popover.component.html
- client/src/app/components/drugs/cvc-drug-popover/cvc-drug-popover.module.ts
- client/src/app/components/genes/gene-popover/gene-popover.component.html
- client/src/app/components/variants/variant-popover/variant-popover.component.html
- client/src/app/generated/civic.apollo.ts
- client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.module.ts
- client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.page.html
- client/src/app/views/drugs/drugs-detail/drugs-detail.component.html
- client/src/app/views/drugs/drugs-detail/drugs-detail.module.ts
- client/src/app/views/genes/genes-detail/genes-summary/genes-summary.module.ts
- client/src/app/views/genes/genes-detail/genes-summary/genes-summary.page.html
- client/src/app/views/variants/variants-detail/variants-summary/variants-summary.module.ts
- client/src/app/views/variants/variants-detail/variants-summary/variants-summary.page.html
> Turn aliases and hgvs descriptions into tag lists

- client/src/app/components/events/event-feed/event-feed.component.html
- client/src/app/components/events/event-feed/event-feed.component.ts
- client/src/app/components/events/event-feed/event-feed.gql
- client/src/app/components/events/event-feed/event-feed.module.ts
- client/src/app/generated/civic.apollo.ts
> Activity feed polls for new activity and will prompt a user to refresh if new events are found

- client/src/app/views/pages/pages-help/pages-help.page.html
- server/config/initializers/graphiql.rb
> add link to GraphiQL on help page and initial example query with explainer

- client/src/app/components/layout/viewer-button/viewer-button.component.html
- client/src/app/components/layout/viewer-button/viewer-button.component.ts
- client/src/app/components/layout/viewer-button/viewer-button.module.ts
- client/src/app/forms/assertion-revise/assertion-revise.module.ts
- client/src/app/forms/assertion-submit/assertion-submit.module.ts
- client/src/app/forms/config/types/cancel-button/cancel-button.type.html
- client/src/app/forms/config/types/cancel-button/cancel-button.type.ts
- client/src/app/forms/config/types/org-submit-button/org-submit-button.module.ts
- client/src/app/forms/config/types/org-submit-button/org-submit-button.type.html
- client/src/app/forms/config/types/org-submit-button/org-submit-button.type.ts
- client/src/app/forms/config/types/submit-button/submit-button.type.html
- client/src/app/forms/config/types/submit-button/submit-button.type.ts
- client/src/app/forms/config/types/variant-input/variant-input.query.gql
- client/src/app/forms/config/wrappers/form-container/form-container.wrapper.less
- client/src/app/forms/evidence-revise/evidence-revise.form.ts
- client/src/app/forms/evidence-revise/evidence-revise.module.ts
- client/src/app/forms/evidence-submit/evidence-submit.module.ts
- client/src/app/forms/gene-revise/gene-revise.module.ts
- client/src/app/forms/source-submit/source-submit.module.ts
- client/src/app/forms/variant-group-revise/variant-group-revise.module.ts
- client/src/app/forms/variant-group-submit/variant-group-submit.module.ts
- client/src/app/forms/variant-revise/variant-revise.module.ts
- client/src/app/forms/variant-submit/variant-submit.form.html
- client/src/app/forms/variant-submit/variant-submit.form.ts
- client/src/app/forms/variant-submit/variant-submit.module.ts
- client/src/app/generated/civic.apollo.ts
- client/src/app/views/variants/variants-home/variants-home.module.ts
- client/src/app/views/variants/variants-home/variants-home.page.html
- client/src/app/views/variants/variants-home/variants-home.page.less
- client/src/app/views/variants/variants-home/variants-home.page.ts
> Create editor-facing "Add Variant" form.

- client/src/app/components/comments/comment-popover/comment-popover.component.html
- client/src/app/components/evidence/evidence-tag/evidence-tag.component.html
- client/src/app/components/flags/flag-popover/flag-popover.component.html
- client/src/app/components/organizations/organization-tag/organization-tag.component.html
- client/src/app/components/revisions/revision-popover/revision-popover.component.html
- client/src/app/components/variant-groups/variant-group-popover/variant-group-popover.component.html
> Consistently disable nested tag popovers

- client/src/app/components/revisions/revision-list/revision-list.component.ts
- client/src/app/components/revisions/revisions-list-and-filter/revisions-list-and-filter.component.html
- client/src/app/components/revisions/revisions-list-and-filter/revisions-list-and-filter.component.ts
- client/src/app/forms/assertion-revise/assertion-revise.form.ts
- client/src/app/forms/evidence-revise/evidence-revise.form.ts
- client/src/app/forms/gene-revise/gene-revise.form.ts
- client/src/app/forms/variant-group-revise/variant-group-revise.form.ts
- client/src/app/forms/variant-revise/variant-revise.form.ts
> Refresh revision lists and detail pages when revisions are proposed or accepted

- server/app/graphql/resolvers/validate_revisions_for_acceptance.rb
> Correct logic for users accepting their own revisions on genes/variants

- server/app/models/actions/suggest_evidence_item_revision.rb
> Include interaction type in list of fields

- server/Gemfile
- server/Gemfile.lock
- server/app/jobs/allele_registry_ids.rb
- server/app/jobs/generate_monthly_tsvs.rb
- server/app/jobs/generate_nightly_tsvs.rb
- server/app/jobs/generate_tsvs.rb
- server/app/jobs/refresh_materialized_views.rb
- server/app/jobs/set_allele_registry_id_single_variant.rb
- server/app/lib/link_adaptors/base.rb
- server/app/models/variant.rb
- server/app/tsv_formatters/assertion_tsv_formatter.rb
- server/app/tsv_formatters/evidence_item_tsv_formatter.rb
- server/app/tsv_formatters/gene_tsv_formatter.rb
- server/app/tsv_formatters/variant_group_tsv_formatter.rb
- server/app/tsv_formatters/variant_tsv_formatter.rb
- server/config/initializers/sidekiq.rb
- server/config/scheduled_tasks.yml
- server/misc_scripts/add_allele_registry_link.rb
* allele registry ids
* refresh materialized views closes #77 
* generate monthly and nightly tsvs
> Begin porting scheduled tasks over to v2

- client/src/app/components/shared/moderate-entity-buttons/moderate-entity-button.ts
- client/src/app/components/shared/moderate-entity-buttons/moderate-entity-buttons.component.html
- client/src/app/generated/civic.apollo.ts
- client/src/app/views/assertions/assertions-detail/assertions-detail.query.gql
- client/src/app/views/assertions/assertions-detail/assertions-detail.view.html
- client/src/app/views/evidence/evidence-detail/evidence-detail.query.gql
- client/src/app/views/evidence/evidence-detail/evidence-detail.view.html
> Show reject button for users' own submissions, even if not an editor

- client/src/app/components/source-suggestions/source-suggestions-table/source-suggestions-table.component.html
- client/src/app/components/source-suggestions/source-suggestions-table/source-suggestions-table.component.ts
- client/src/app/components/source-suggestions/source-suggestions-table/source-suggestions-table.query.gql
- client/src/app/generated/civic.apollo.ts
- client/src/app/generated/server.field-policies.ts
- client/src/app/generated/server.model.graphql
- client/src/app/generated/server.schema.json
- server/app/graphql/resolvers/browse_source_suggestions.rb
- server/app/graphql/types/browse_tables/source_suggestions_sort_columns.rb
- server/app/graphql/types/entities/source_suggestion_type.rb
> allow sorting by creation date in the source suggestion table

- client/src/app/components/assertions/assertions-table/assertions-table.component.html
- client/src/app/components/evidence/evidence-table/evidence-table.component.html
- client/src/app/components/evidence/evidence-table/evidence-table.component.ts
- client/src/app/components/source-suggestions/source-suggestions-table/source-suggestions-table.component.html
Moved the interaction type icon from the drug list cell to its own column.
> adds drug interaction type column to evidence, assertions tables

- server/app/graphql/types/queries/typeahead_queries.rb
> dedup alias and primary matches in gene typeahead

- client/src/app/forms/evidence-revise/evidence-revise.form.ts
- client/src/app/forms/evidence-submit/evidence-submit.form.ts
> Handle case when a drug interaction type has been set, but is no longer valid

- client/src/app/core/utilities/enum-tooltips/get-evidence-enum-tooltip.ts
- client/src/app/forms/config/components/form-errors-alert/form-errors-alert.component.ts
- client/src/app/forms/config/types/clinical-significance-select/clinical-significance-select.type.ts
- client/src/app/forms/config/types/evidence-direction-select/evidence-direction-select.type.ts
- server/app/graphql/mutations/submit_assertion.rb
- server/app/graphql/mutations/submit_evidence_item.rb
- server/app/graphql/mutations/suggest_assertion_revision.rb
- server/app/graphql/mutations/suggest_evidence_item_revision.rb
- server/app/graphql/mutations/suggest_source.rb
- server/app/models/input_adaptors/assertion_input_adaptor.rb
* display evidence item validation errors when submitting assertions wth invalid evidence
> Oncogenic Assertion Improvements

- server/app/graphql/resolvers/browse_variants.rb
> Make variant name search in browse table wildcard match in both directions

- server/app/graphql/types/entities/source_type.rb
- server/app/models/source.rb
- server/db/migrate/20220816205024_update_source_browse_table_rows_to_version_6.rb
- server/db/schema.rb
- server/db/views/source_browse_table_rows_v06.sql
> Author list improvements for sources

- client/src/app/core/utilities/mutation-state-wrapper.ts
- client/src/app/forms/assertion-submit/assertion-submit.form.ts
- client/src/app/forms/complex-molecular-profile-input/complex-molecular-profile-input.form.ts
- client/src/app/forms/config/types/disease-input/disease-input.type.ts
- client/src/app/forms/config/types/drug-input/drug-input.type.ts
- client/src/app/forms/config/types/variant-input/variant-input.type.ts
- client/src/app/forms/evidence-submit/evidence-submit.form.ts
- client/src/app/forms/source-submit/source-submit.form.ts
- client/src/app/forms/variant-group-submit/variant-group-submit.form.ts
- client/src/app/forms/variant-revise/variant-revise.form.html
- client/src/app/forms/variant-revise/variant-revise.form.ts
- client/src/app/forms/variant-revise/variant-revise.query.gql
- client/src/app/forms/variant-submit/variant-submit.form.ts
- client/src/app/generated/civic.apollo.ts
- server/app/graphql/mutations/suggest_variant_revision.rb
> Give the user feedback when no new revisions are created

- client/src/app/core/utilities/mutation-state-wrapper.ts
- client/src/app/forms/assertion-submit/assertion-submit.form.ts
- client/src/app/forms/complex-molecular-profile-input/complex-molecular-profile-input.form.ts
- client/src/app/forms/config/types/disease-input/disease-input.type.ts
- client/src/app/forms/config/types/drug-input/drug-input.type.ts
- client/src/app/forms/config/types/variant-input/variant-input.type.ts
- client/src/app/forms/evidence-submit/evidence-submit.form.ts
- client/src/app/forms/source-submit/source-submit.form.ts
- client/src/app/forms/variant-group-submit/variant-group-submit.form.ts
- client/src/app/forms/variant-revise/variant-revise.form.html
- client/src/app/forms/variant-revise/variant-revise.form.ts
- client/src/app/forms/variant-revise/variant-revise.query.gql
- client/src/app/forms/variant-submit/variant-submit.form.ts
- client/src/app/generated/civic.apollo.ts
- server/app/graphql/mutations/suggest_variant_revision.rb
Reverts griffithlab/civic-v2#613
> Revert "Give the user feedback when no new revisions are created"

- client/src/app/core/utilities/enum-tooltips/get-evidence-enum-tooltip.ts
- client/src/app/forms/config/states/assertion.state.ts
- client/src/app/forms/config/types/evidence-direction-select/evidence-direction-select.type.ts
- server/app/validators/assertion_validator.rb
closes #630 
Do we need corresponding updates to the docs site?
> Remove "Does Not Support" option for Predisposing and Oncogenic Assertions

- client/src/app/components/revisions/revision-list/revision-list.component.html
> Add special handling for NCCN guideline revisions

- client/src/app/forms/source-submit/source-submit.form.html
- client/src/app/forms/source-submit/source-submit.form.ts
- client/src/app/views/sources/sources-routing.module.ts
- server/app/graphql/mutations/suggest_source.rb
> Reload submit source form on navigation to same route.

- client/src/app/views/variants/variants-detail/variants-summary/variants-summary.page.html
> fix clinvar linkout in the NONE FOUND case

- server/app/graphql/resolvers/top_level_evidence_items.rb
> do not attempt to look for misspellings unless there are no matches

- server/app/lib/scrapers/ash.rb
- server/app/lib/scrapers/ash_record_response.rb
- server/db/migrate/20230113171643_backfill_ash.rb
- server/db/schema.rb
In addition to author list and title, pull in the abstract text for display on source pages.
> Scrape abstract text for ASH sources

- client/src/app/components/molecular-profiles/molecular-profile-table/molecular-profile-table.component.html
- client/src/app/components/molecular-profiles/molecular-profile-table/molecular-profile-table.component.ts
- client/src/app/components/molecular-profiles/molecular-profile-table/molecular-profile-table.query.gql
- client/src/app/generated/civic.apollo-helpers.ts
- client/src/app/generated/civic.apollo.ts
- client/src/app/generated/server.model.graphql
- client/src/app/generated/server.schema.json
- server/app/graphql/resolvers/browse_molecular_profiles.rb
- server/app/graphql/types/browse_tables/browse_molecular_profile_type.rb
- server/app/graphql/types/browse_tables/molecular_profiles_sort_columns.rb
- server/db/migrate/20230113165605_update_molecular_profile_browse_table_rows_to_version_9.rb
- server/db/schema.rb
- server/db/views/molecular_profile_browse_table_rows_v09.sql
* Add MP name filtering to MP browse table
* Add sortable variant count to MP browse
> Browse table updates

- client/src/app/forms/config/types/disease-input/disease-input.query.gql
- client/src/app/forms/config/types/disease-input/disease-input.type.ts
- client/src/app/generated/civic.apollo.ts
- client/src/app/generated/server.model.graphql
- client/src/app/generated/server.schema.json
- server/app/graphql/mutations/add_disease.rb
Treat DOID as a string on input and validate with a regex instead of treating it like an int.
> Accomodate Leading Zeroes in DOID entry

- server/app/graphql/types/queries/source_queries.rb
- server/app/models/source.rb
> Validate Citation ID formatting

- server/app/graphql/resolvers/top_level_assertions.rb
- server/app/graphql/resolvers/top_level_evidence_items.rb
- server/app/graphql/resolvers/top_level_genes.rb
> Fix a few more places where we were using the eid -> variant association

- client/src/app/components/genes/my-gene-info/my-gene-info.component.html
- client/src/app/components/genes/my-gene-info/my-gene-info.component.less
- client/src/app/components/genes/my-gene-info/my-gene-info.module.ts
> Update formatting of MyGeneInfo Overview to avoid overlap on smaller screens

- server/app/models/mane_select_transcript.rb
> Handle cases where none of the allele registry transcripts are tagged as MANE select

- client/src/app/components/diseases/my-disease-info/my-disease-info.component.html
- client/src/app/components/diseases/my-disease-info/my-disease-info.component.less
- client/src/app/components/diseases/my-disease-info/my-disease-info.component.ts
- client/src/app/components/diseases/my-disease-info/my-disease-info.module.ts
- client/src/app/generated/civic.apollo-helpers.ts
- client/src/app/generated/civic.apollo.ts
- client/src/app/generated/server.model.graphql
- client/src/app/generated/server.schema.json
- client/src/app/views/diseases/diseases-detail/diseases-summary/diseases-summary.component.html
- client/src/app/views/diseases/diseases-detail/diseases-summary/diseases-summary.component.ts
- client/src/app/views/diseases/diseases-detail/diseases-summary/diseases-summary.module.ts
- client/src/app/views/diseases/diseases-detail/diseases-summary/diseases-summary.query.gql
- server/app/graphql/types/entities/disease_type.rb
- server/app/graphql/types/entities/my_disease_info_type.rb
- server/app/models/my_disease_info.rb
> MyDisease.info integration

- client/src/app/views/pages/pages-about/pages-about.page.html
> removed duplicate mission statement block; added breakpoint layouts

- client/src/app/forms2/components/entity-tag-popover/entity-tag-popover.component.html
- client/src/app/forms2/components/entity-tag-popover/entity-tag-popover.component.ts
- client/src/app/forms2/components/entity-tag-popover/entity-tag-popover.module.ts
- client/src/app/forms2/types/evidence-select/evidence-select.type.ts
- client/src/app/forms2/types/variant-select/variant-select.type.ts
gene, variant, evidence tags in evidence/variant managers now working
> fixes evidence/variant managers' tag popovers

- client/src/app/forms2/config/gene-revise/gene-revise.form.config.ts
- client/src/app/forms2/config/molecular-profile-revise/molecular-profile-revise.form.config.ts
> Make some form fields not required

- client/src/app/forms2/config/assertion-revise/assertion-revise.form.config.ts
- client/src/app/forms2/config/assertion-submit/assertion-submit.form.config.ts
- client/src/app/forms2/config/evidence-revise/evidence-revise.form.config.ts
- client/src/app/forms2/config/evidence-submit/evidence-submit.form.config.ts
- client/src/app/forms2/config/gene-revise/gene-revise.form.config.ts
- client/src/app/forms2/config/molecular-profile-revise/molecular-profile-revise.form.config.ts
- client/src/app/forms2/config/source-submit/source-submit.form.config.ts
- client/src/app/forms2/config/variant-revise/variant-revise.form.config.ts
- client/src/app/forms2/config/variantgroup-revise/variantgroup-revise.form.config.ts
- client/src/app/forms2/config/variantgroup-submit/variantgroup-submit.form.config.ts
- client/src/app/forms2/types/cancel-button/cancel-buton.type.html
- client/src/app/forms2/types/cancel-button/cancel-button.module.ts
- client/src/app/forms2/types/cancel-button/cancel-button.type.less
- client/src/app/forms2/types/cancel-button/cancel-button.type.ts
- client/src/app/forms2/types/form-types.module.ts
> Add cancel button to all forms

- client/src/app/forms2/config/assertion-revise/assertion-revise.form.config.ts
- client/src/app/forms2/config/evidence-revise/evidence-revise.form.config.ts
- client/src/app/forms2/types/direction-select/direction-select.type.ts
- client/src/app/forms2/types/significance-select/significance-select.type.ts
> ignore first evidence type change event when on a revise form

- client/src/app/core/utilities/molecular-profile-parser.ts
- client/src/app/forms2/types/molecular-profile-select/mp-expression-editor/mp-editor-popover-help.component.html
- client/src/app/forms2/types/molecular-profile-select/mp-expression-editor/mp-expression-editor.component.html
- client/src/app/forms2/types/molecular-profile-select/mp-expression-editor/mp-expression-editor.component.ts
This PR applies the updated help text and MP expression examples provided by the team. Also made a few UI improvements like normalized hover/click behavior with the help text and action buttons.
> MP Editor help text, expression examples updated

- client/src/app/components/layout/quicksearch/quicksearch-component.html
- client/src/app/components/layout/quicksearch/quicksearch-component.ts
- client/src/app/components/layout/quicksearch/quicksearch.module.ts
- server/db/schema.rb
use existing pipes and helpers to determine quicksearch icon color
closes #814
> Fix icon colors in quicksearch

- client/src/app/forms2/config/evidence-submit/evidence-submit.form.html
- client/src/app/forms2/config/evidence-submit/evidence-submit.form.module.ts
- client/src/app/forms2/config/evidence-submit/evidence-submit.form.ts
- client/src/app/forms2/config/evidence-submit/existing-evidence-count.gql
- client/src/app/generated/civic.apollo.ts
> Display a warning when users enter potentially duplicate Evidence

- client/src/app/components/shared/tab-navigation/tab-navigation.component.html
- client/src/app/components/shared/tab-navigation/tab-navigation.component.ts
- client/src/app/generated/civic.apollo.ts
- client/src/app/views/assertions/assertions-detail/assertions-detail.view.ts
- client/src/app/views/evidence/evidence-detail/evidence-detail.view.ts
- client/src/app/views/genes/genes-detail/genes-detail.view.ts
- client/src/app/views/molecular-profiles/molecular-profiles-detail/molecular-profiles-detail.view.ts
- client/src/app/views/sources/sources-detail/sources-detail.query.gql
- client/src/app/views/sources/sources-detail/sources-detail.view.html
- client/src/app/views/sources/sources-detail/sources-detail.view.ts
- client/src/app/views/variant-groups/variant-groups-detail/variant-groups-detail.view.ts
- client/src/app/views/variants/variants-detail/variants-detail.view.ts
- server/app/models/source.rb
> Show badge indicating number of comments on "Comments" tab nav

- client/src/app/forms/user-profile/user-profile.form.html
- client/src/app/forms/user-profile/user-profile.module.ts
- server/app/graphql/mutations/edit_user.rb
- server/app/models/user.rb
> Add hinting and validation for users entering their social media handles

- examples/fetch_acmg_code.R
- examples/fetch_all_variants.py
This is easier than linking people on the mailing list to Gists and we can expand and improve them over time.
> Add some very rudimentary API usage examples to the repo

- server/app/tsv_formatters/variant_tsv_formatter.rb
This is a request originating from the meeting with the AUGMET folks
> Add single variant MP id to variant TSV for ease of fetching EIDs

- client/src/app/forms2/components/entity-select/entity-select.component.html
- client/src/app/forms2/components/entity-select/entity-select.component.less
- client/src/app/forms2/components/entity-select/entity-select.component.ts
- client/src/app/forms2/components/entity-select/entity-select.module.ts
- client/src/app/forms2/types/variant-select/variant-quick-add/variant-quick-add.form.ts
- client/src/app/forms2/types/variant-select/variant-select.module.ts
- client/src/app/forms2/types/variant-select/variant-select.type.html
- client/src/app/forms2/types/variant-select/variant-select.type.less
- client/src/app/forms2/types/variant-select/variant-select.type.ts
Allow a user to pass in a custom function for determining when the add form is displayed. Provide a custom rule for Variants.
closes #890
> Allow customizing when the "Add" form is displayed in Entity Select

- server/app/admin/therapies_admin.rb
- server/app/models/therapy.rb
> small admin fixes: display error message on duplicate ncit ids, add search

- client/src/app/components/sources/source-popover/source-popover.component.html
- client/src/app/components/sources/source-popover/source-popover.query.gql
- client/src/app/generated/civic.apollo.ts
- client/src/app/views/sources/sources-detail/sources-summary/sources-summary.page.html
- client/src/app/views/sources/sources-detail/sources-summary/sources-summary.query.gql
- server/app/lib/scrapers/asco_query_response.rb
- server/app/lib/scrapers/ash_record_response.rb
- server/app/lib/scrapers/pub_med_response.rb
- server/app/scrapers/asco_query_response.rb
- server/app/scrapers/pub_med_response.rb
> Update how Source citation is constructed and information displayed on detail pages and in popovers

- server/app/admin/diseases_admin.rb
- server/app/admin/therapies_admin.rb
- server/app/graphql/resolvers/top_level_therapies.rb
- server/app/graphql/types/queries/typeahead_queries.rb
- server/app/models/disease.rb
- server/app/models/therapy.rb
- server/app/validators/deprecation_validator.rb
- server/db/migrate/20231024150741_add_deprecate_column_to_diseases.rb
- server/db/migrate/20231024151822_add_deprecate_column_to_therapy.rb
- server/db/migrate/20231024153516_update_disease_browse_table_rows_to_version_5.rb
- server/db/schema.rb
- server/db/views/disease_browse_table_rows_v05.sql
> Allow disease and therapies to be deprecated and exclude those from views and typeaheads

- client/src/app/components/revisions/revision-list/revision-list.component.ts
> clear comment after revision accept/reject succeeds

- server/db/migrate/20231027155450_update_variant_browse_table_rows_to_version_13.rb
- server/db/schema.rb
- server/db/views/variant_browse_table_rows_v13.sql
> include variants with no eids as long as they are not deprecated

- client/src/app/components/events/event-feed/event-feed.component.html
"events && Action" -> "Action"
> fix event-feed sidebar list title

- server/app/models/actions/extract_references.rb
fix scope on method call. closes #937
> fix hash completion in comment typeahead

- client/src/app/forms/types/variant-select/variant-quick-add/variant-quick-add.form.ts
> Fix variant quick add not working

- client/src/app/views/genes/genes-detail/genes-summary/genes-summary.page.html
> Update DGIdb linkouts to work with v5

- client/src/app/components/organizations/organizations-table/organizations-table.component.html
- client/src/app/components/organizations/organizations-table/organizations-table.query.gql
- client/src/app/components/users/users-table/users-table.component.html
- client/src/app/components/users/users-table/users-table.query.gql
- client/src/app/core/pipes/timeago-formatter.ts
- client/src/app/generated/civic.apollo-helpers.ts
- client/src/app/generated/civic.apollo.ts
- client/src/app/generated/server.model.graphql
- client/src/app/generated/server.schema.json
- server/app/graphql/resolvers/top_level_users.rb
- server/app/graphql/types/entities/organization_type.rb
- server/app/graphql/types/entities/user_type.rb
- server/app/models/activities/base.rb
- server/app/models/event.rb
- server/db/migrate/20240110000025_add_last_org_action_timestamp.rb
- server/db/schema.rb
* handle null case in timeago pipe to avoid NaN when the timestamp doesn't exist
* port to use activities instead of events
* make sure timestamp is updated even if user validation fails
* add caching for org timestamp
closes #974
> Improvements to Most Recent Event timestamps for orgs and users

- server/app/graphql/resolvers/top_level_evidence_items.rb
Fixes duplicate EIDs when joining to therapies
> Add distinct clause on EID browse

- client/src/app/forms/config/assertion-revise/assertion-revise.form.ts
Form's state was missing its formMode, assertion-revise's direction & significance fields now populate without error.
> fixes direction & significance population error in assertion-revise form

- server/app/models/actions/merge_accounts.rb
- server/app/models/notification.rb
- server/app/models/subscription.rb
Will want to hook it into the Admin UI at some point, but this should at least make it easier when we get merge requests.
> Introduce Account Merge Tool

- server/app/lib/link_adaptors/factor_variant.rb
- server/app/lib/link_adaptors/gene_variant.rb
> add link adaptors for variant subtypes

- client/src/app/forms/types/therapy-select/therapy-select.type.html
> Fix formatting of NCIt Code and Alias search results in therapy typeahead

- client/src/app/components/features/features-table/features-table.component.html
- client/src/app/components/features/features-table/features-table.component.ts
- client/src/app/components/features/features-table/features-table.query.gql
- client/src/app/generated/civic.apollo-helpers.ts
- client/src/app/generated/civic.apollo.ts
- client/src/app/generated/server.model.graphql
- client/src/app/generated/server.schema.json
- server/app/graphql/resolvers/browse_features.rb
- server/app/graphql/types/browse_tables/browse_feature_type.rb
- server/app/graphql/types/browse_tables/features_sort_columns.rb
- server/app/models/feature.rb
- server/db/migrate/20240726163525_update_feature_browse_table_rows_to_version_6.rb
- server/db/schema.rb
- server/db/views/feature_browse_table_rows_v06.sql
closes #1077
This adds full name as a column in the Features browse table, its sortable and filterable as well. Additionally it indexes the full name of Factor features in elasticsearch so it will be matchable in the quicksearch box.
> Add full name to feature browse table

- server/Gemfile
- server/Gemfile.lock
- server/db/migrate/20240822154958_upgrade_solid_errors.rb
- server/db/migrate/20240822155113_solid_error_fingerprint_non_nullable.rb
- server/db/schema.rb
with rails 7.2 coming out, this will begin working correctly once we update.
db migrations outlined in guide here: https://github.com/fractaledmind/solid_errors/blob/main/UPGRADE.md
> update to newest version of solid_errors

- client/src/app/views/variants/variants-revise/variants-revise.module.ts
- client/src/app/views/variants/variants-revise/variants-revise.view.html
> display feature name on variant revise page header

- server/app/lib/importer/disease_ontology_mirror.rb
We were checking for usage in revisions before deleting in the "unprocessed doids" case but not in the case where there just wasn't a doid at all. This pulls the logic out into a shared method and uses the same logic both places.
closes #1156
> check for disease usage in revisions in the case where there is no DOID

- server/app/graphql/types/queries/typeahead_queries.rb
- server/app/jobs/populate_fusion_coordinates.rb
- server/app/models/variants/fusion_variant.rb
* typeahead ordering
* optional DOID: prefix
* don't try to populate coordinates when no transcript is curated
* make callback a public method
> Various fixes

- server/app/lib/link_adaptors/fusion_variant.rb
- server/app/models/frontend_router.rb
* fix links when id is missing; now will result in a bad request rather than a 500
* add fusion variant adapter
> Small fixes for permalink redirects

- server/app/jobs/populate_fusion_coordinates.rb
- server/app/lib/scrapers/ensembl_api_helpers.rb
- server/app/models/hgvs_description.rb
> Various updates to ensure that GRCh38 coordinates work

- server/app/models/hgvs_description.rb
Was seeing errors in the logs where we were trying to set an allele registry id for fusion variants and it was blowing up. This will just immediately return if its not a variant we support.
> when generating an hgvs string, bail out early unless its a gene variant
