client/src/app/forms/config/types/drug-input/drug-input.type.html
server/app/graphql/types/queries/typeahead_queries.rb

Closes #338.
Closes #342 
This PR also makes a change to the drug and disease typeahead that would prioritize direct name matches over alias matches. This change leads to a larger number of queries though since alias tables will be queried separately.

Fix drug typeahead

---

client/src/app/components/layout/quicksearch/quicksearch-component.html
server/app/graphql/resolvers/quicksearch.rb
server/app/models/variant.rb

We will likely want to tweak and tune the quicksearch in general to be intuitive across all the data types and to search all the fields users are interested in but for the immediate case, this closes #378

include gene name in variant quick search results and indexing.;

---

client/src/app/components/layout/viewer-button/viewer-button.component.html

The `Your Profile` menu item only linked the actual `Your Profile` text, so anywhere else besides the text did nothing. This PR moves the routerLink to the list element so clicking anywhere on the list item will invoke the route change.
Closes #406.

viewer-button Your Profile link extends to entire menu-item area

---

server/app/lib/graphql_analytics_tracer.rb

Also spell referrer "correctly" even though its out of spec: https://en.wikipedia.org/wiki/HTTP_referer

Fix up typos in analytics request tracking

---

client/src/app/generated/server.model.graphql
client/src/app/generated/server.schema.json
client/src/app/views/pages/pages-help/pages-help.page.html
docs/config.yml
server/app/graphql/mutations/add_remote_citation.rb

* Convert instances of `CiVIC` to `CIViC`.
* Bonus capitalization of `Twitter` and revise the `@CIViCdb` handle to match how it appears on Twitter.

Consistent capitalization of "CIViC".

---

client/src/app/components/events/event-feed/event-feed.component.ts
client/src/app/components/events/homepage-event-feed/homepage-event-feed.component.html
client/src/app/components/events/homepage-event-feed/homepage-event-feed.component.less
client/src/app/components/events/homepage-event-feed/homepage-event-feed.component.ts
client/src/app/components/events/homepage-event-feed/homepage-event-feed.module.ts
client/src/app/views/curation/curation-activity/curation-timeline/curation-timeline.page.html
client/src/app/views/welcome/welcome.component.html
client/src/app/views/welcome/welcome.module.ts

Closes #448 
This PR introduces a new component for the homepage activity feed which continues to have auto-refresh enabled but instead of a "load more" button it adds a link to the full activity feed.
The full activity feed (and the event feed on user/org profiles) will no longer auto-refresh. Ultimately, we will add a button on these feeds to show when new events are available and to reload the feed manually.

Remove auto-refresh from full activity feed

---

client/src/app/forms/config/types/ensembl-input/ensembl-input.type.ts

Fixes the issue where the variant revise form was forcing people to select an ensembl version

null is a valid value for ensembl version

---

client/src/app/views/welcome/welcome.component.html
client/src/app/views/welcome/welcome.component.less
client/src/app/views/welcome/welcome.component.ts

We can revisit this later if we want something more detailed or a whole page dedicated to the changelog in the future.
closes #459

display version and release notes on homepage

---

server/app/graphql/types/entities/user_type.rb

This acts as a stopgap to speed up the "contributors" table in the short term. Longer term we'll likely want to make it a materialized view, or incorporate it into the community page somehow.

cache user stats hash

---

client/src/app/components/sources/sources-table/sources-table.component.html
client/src/app/components/sources/sources-table/sources-table.query.gql
client/src/app/generated/civic.apollo.ts
client/src/app/generated/server.field-policies.ts
client/src/app/generated/server.model.graphql
client/src/app/generated/server.schema.json
server/app/graphql/resolvers/browse_sources.rb
server/app/graphql/types/browse_tables/browse_source_type.rb
server/app/graphql/types/browse_tables/sources_sort_columns.rb
server/app/graphql/types/entities/variant_type.rb
server/app/jobs/refresh_materialized_views.rb
server/db/migrate/20220505150407_update_source_browse_table_rows_to_version_4.rb
server/db/migrate/20220511200531_update_source_browse_table_rows_to_version_5.rb
server/db/schema.rb
server/db/views/source_browse_table_rows_v04.sql
server/db/views/source_browse_table_rows_v05.sql

The source browse table now includes "open" suggestion count as a column. Furthermore the view returns sources that have at least 1 non-rejected evidence item OR one new source suggestion.

Include suggeston count in source browse table

---

client/src/app/forms/config/types/variant-input/variant-input.module.ts
client/src/app/forms/config/types/variant-input/variant-input.query.gql
client/src/app/forms/config/types/variant-input/variant-input.type.html
client/src/app/forms/evidence-revise/evidence-revise.form.ts
client/src/app/forms/evidence-revise/evidence-revise.module.ts
client/src/app/forms/evidence-revise/evidence-revise.query.gql
client/src/app/generated/civic.apollo.ts

On the Variant Revise form, the gene will now be explicitly displayed and the variant typeahead will be scoped to the selected gene.
If you wish to move the EID to an entirely different gene, you will need to select that explicitly, then the variant.
Additionally, the variant typeahead will now display the variant's ID as well as any aliases to help ensure the correct variant is selected.
closes #522

Improve form clarity when reparenting EIDs

---

client/src/app/components/events/event-feed/event-feed.component.ts
client/src/app/components/events/event-feed/event-feed.gql
client/src/app/components/events/homepage-event-feed/homepage-event-feed.component.ts
client/src/app/generated/civic.apollo.ts
client/src/app/generated/server.model.graphql
client/src/app/generated/server.schema.json
client/src/app/views/curation/curation-activity/curation-timeline/curation-timeline.page.html
server/app/graphql/resolvers/top_level_events.rb
server/app/models/constants.rb

They will still be shown on the event feeds for individual entities.

filter out civicbot events on homepage/main activity feed

---

client/src/app/forms/config/components/org-selector-btn-group/org-selector-btn-group.component.html
client/src/app/forms/config/components/org-selector-btn-group/org-selector-btn-group.component.ts
client/src/app/forms/config/components/org-selector-btn-group/org-selector-btn-group.module.ts
client/src/app/forms/config/components/org-selector-btn-group/org-selector-btn.directive.ts
client/src/app/forms/config/types/org-submit-button/org-submit-button.type.ts
client/src/main.ts

The organizations-select-button component  is used all over the place to append a dropdown to various curation action buttons. It has an issue coordinating the state of its 'for [org icon]' dropdown menu button and the transcluded button after which it is appended:
Additionally, the form field type `org-submit-button` has an issue updating its disabled state based on the current state of the form model, sometimes requiring the user to create a UI event (mouse movement, tabbing out of a text field) to cause the submit button to display as enabled.
This PR:
- fixes disabled state coordination between org-select-btn's appended select button and its embedded button
- forces the the `org-submit-button` field type to perform a view refresh on all validity events from the form. Now it will …

fix organization select button and its field type

---

client/package.json
client/src/app/components/shared/attribute-tag/attribute-tag.component.html
client/src/app/components/shared/attribute-tag/attribute-tag.component.less
client/src/app/components/shared/attribute-tag/attribute-tag.component.ts
client/src/app/components/shared/attribute-tag/attribute-tag.module.ts
client/src/app/core/pipes/evidence-enum-display-type.ts
client/src/app/core/pipes/evidence-enum-tooltip.pipe.ts
client/src/app/core/pipes/pipes.module.ts
client/src/app/core/utilities/enum-formatters/format-evidence-enum.ts
client/src/app/core/utilities/enum-tooltips/get-evidence-enum-tooltip.ts
client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.module.ts
client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.page.html
client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.page.less
client/src/app/views/evidence/evidence-detail/evidence-summary/evidence-summary.module.ts
client/src/app/views/evidence/evidence-detail/evidence-summary/evidence-summary.page.html
client/src/app/views/evidence/evidence-detail/evidence-summary/evidence-summary.page.less
client/src/app/views/genes/genes-detail/genes-summary/genes-summary.page.html
client/src/app/views/genes/genes-detail/genes-summary/genes-summary.page.less
client/src/app/views/variants/variants-detail/variants-summary/variants-summary.module.ts
client/src/app/views/variants/variants-detail/variants-summary/variants-summary.page.html
client/src/app/views/variants/variants-detail/variants-summary/variants-summary.page.less
client/src/themes/overrides/descriptions-overrides.less
client/yarn.lock

Updates evidence, assertion, gene, variant summary page layouts to improve readability:
- labels are slightly bolder, most values displayed as tags to better differentiate labels & values
- all label/value are displayed horizontally, adjacent to each other instead of a mix of vertical/horizontal placement
- added breakpoint hints to description-item tags so that layouts remain readable from narrow to very wide displays
Additional updates:
- evidence & assertion attribute tags show tooltips, as with civic v1
- page layouts switched from using nz-space to nz-row/col for handling spacing between blocks, which is recommended
closes #563
closes #558

improve readability of entity summary page details

---

client/src/app/components/variants/variants-menu/variants-menu.component.html
client/src/app/components/variants/variants-menu/variants-menu.component.ts

This fixes two issues with the variant menu on Gene pages
* The `select` widths are now fixed so the menus don't jump around as you pick different options
* The variant status filter actually fires when you change its value instead of being delayed.
Closes #529

Fix variant menu behavior

---

client/src/app/layout/layout.component.html
client/src/app/layout/layout.component.less
client/src/app/views/assertions/assertions-home/assertions-home.page.html
client/src/app/views/clinical-trials/clinical-trials-home/clinical-trials-home.page.html
client/src/app/views/diseases/diseases-home/diseases-home.page.html
client/src/app/views/evidence/evidence-home/evidence-home.page.html
client/src/app/views/genes/genes-home/genes-home.page.html
client/src/app/views/molecular-profiles/molecular-profiles-home/molecular-profiles-home.page.html
client/src/app/views/sources/sources-home/sources-home.page.html
client/src/app/views/users/users-home/users-home.page.html
client/src/app/views/variant-groups/variant-groups-home/variant-groups-home.page.html
client/src/app/views/variant-types/variant-types-home/variant-types-home.page.html
client/src/app/views/variants/variants-home/variants-home.page.html
client/src/themes/overrides/entity-page-header.overrides.less

The viewer area no longer wraps below the other header components, and the home page headers behave better at narrow window widths.
Closes #544

fixes app header and entity home page header wrapping at narrow window widths

---

client/src/app/components/assertions/assertions-table/assertions-table.component.html
client/src/app/components/clinical-trials/clinical-trials-table/clinical-trials-table.component.html
client/src/app/components/diseases/diseases-table/diseases-table.component.html
client/src/app/components/drugs/drugs-table/drugs-table.component.html
client/src/app/components/evidence/evidence-table/evidence-table.component.html
client/src/app/components/genes/genes-table/genes-table.component.html
client/src/app/components/molecular-profiles/molecular-profile-table/molecular-profile-table.component.html
client/src/app/components/organizations/organizations-table/organizations-table.component.html
client/src/app/components/phenotypes/phenotypes-table/phenotypes-table.component.html
client/src/app/components/sources/sources-table/sources-table.component.html
client/src/app/components/users/users-table/users-table.component.html
client/src/app/components/variant-groups/variant-groups-table/variant-groups-table.component.html
client/src/app/components/variant-types/variant-types-table/variant-types-table.component.html
client/src/app/components/variants/variants-table/variants-table.component.html
client/src/app/core/utilities/get-entity-color.ts
client/src/app/layout/layout.component.html
client/src/app/layout/layout.component.less
client/src/app/views/assertions/assertions-home/assertions-home.page.html
client/src/app/views/clinical-trials/clinical-trials-home/clinical-trials-home.page.html
client/src/app/views/diseases/diseases-home/diseases-home.page.html
client/src/app/views/evidence/evidence-home/evidence-home.page.html
client/src/app/views/genes/genes-home/genes-home.page.html
client/src/app/views/molecular-profiles/molecular-profiles-home/molecular-profiles-home.page.html
client/src/app/views/sources/sources-home/sources-home.page.html
client/src/app/views/users/users-home/users-home.page.html
client/src/app/views/variant-groups/variant-groups-home/variant-groups-home.page.html
client/src/app/views/variant-types/variant-types-home/variant-types-home.page.html
client/src/app/views/variants/variants-home/variants-home.page.html
client/src/themes/overrides/entity-page-header.overrides.less

The entity icons in table titles are redundant, because the first column of the table displays tags with the entity icons. 
Switched column header entity icons to monochrome, as color icons should be reserved for placement on elements that represent an actual entity (e.g. tags, cards, summary pages), and not an aggregate of entities.

removes entity table title icons, entity icons in col headers switched to monochrome

---

client/src/app/components/shared/moderate-entity-buttons/moderate-entity-buttons.component.html
client/src/app/forms/complex-molecular-profile-input/complex-molecular-profile-input.form.ts
client/src/app/forms/config/components/org-selector-btn-group/org-selector-btn-group.component.html
client/src/app/forms/config/components/org-selector-btn-group/org-selector-btn-group.component.less
client/src/app/forms/config/components/org-selector-btn-group/org-selector-btn-group.component.ts
client/src/app/forms/config/components/org-selector-btn-group/org-selector-btn-group.module.ts
client/src/app/forms/config/components/org-selector-btn-group/org-selector-btn.directive.ts
client/src/app/forms/config/types/org-submit-button/org-submit-button.type.html
client/src/app/forms/evidence-submit/evidence-submit.form.html
client/src/app/views/evidence/evidence-add/evidence-submit/evidence-submit.module.ts

The org-selector-btn has had several problems w/ keeping the selector button's classes and disabled/hidden state synchronized with the transcluded button it's attached to. This update fixes all those problems by copying all class updates from the transcluded button (with the cvcOrgSelectorBtn directive), as well as disabled and hidden state changes. Also fixes some small style issues when a button w/ 'primary' nzType also has nzDanger applied, inside an nz-button-group.

fix org-selector-btn synchronization of class, disabled, hidden

---

client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.page.html

closes #680 
We will want to verify that older (pre v2) assertions are correctly set to null rather than false for types other than predictive

distinguish between false and undefined

---

server/app/graphql/mutations/add_variant.rb

Closes #566 
In the refactored forms we should add an indicator when a new variant isn't created because one with the same name/alias already exists. Currently it just inserts the existing Variant into the form.

Lookup Variant by alias before creating a new one

---

client/src/app/components/layout/quicksearch/quicksearch-component.html

Remove nzLabel on the quicksearch dropdown options to remove tooltip

---

client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.page.html
client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.page.less
client/src/app/views/evidence/evidence-detail/evidence-summary/evidence-summary.page.html
client/src/app/views/evidence/evidence-detail/evidence-summary/evidence-summary.page.less

This prevents the text box from pushing the tables off the bottom of the page.
closes #749

Long evidence and assertion descriptons will overflow into scroll

---

client/.prettierrc.json
client/src/app/components/shared/empty-value/empty-value.component.html
client/src/app/components/shared/empty-value/empty-value.component.less
client/src/app/components/shared/empty-value/empty-value.component.ts
client/src/app/components/shared/empty-value/empty-value.module.ts
client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.module.ts
client/src/app/views/assertions/assertions-detail/assertions-summary/assertions-summary.page.html
client/src/app/views/evidence/evidence-detail/evidence-summary/evidence-summary.module.ts
client/src/app/views/evidence/evidence-detail/evidence-summary/evidence-summary.page.html
client/src/app/views/molecular-profiles/molecular-profiles-detail/molecular-profiles-summary/molecular-profiles-summary.module.ts
client/src/app/views/molecular-profiles/molecular-profiles-detail/molecular-profiles-summary/molecular-profiles-summary.page.html

Direction and Significance N/A attribute displays on Evidence summaries now show a text 'Not applicable'. These attribute displays now use an empty-value component that can help standardize the display N/A, Unspecified, Missing messages throughout the app. I also similarly updated the rest of the Evidence attributes w/ potentially empty or N/A values and applied the same updates to Assertions and Molecular Profile summary templates.

Fixes [N/A N/A] attribute tag display issue

---

client/src/app/forms2/config/assertion-submit/assertion-submit.form.config.ts
client/src/app/forms2/types/evidence-select/evidence-manager/evidence-manager.component.html
client/src/app/forms2/types/evidence-select/evidence-manager/evidence-manager.component.ts
client/src/app/forms2/types/evidence-select/evidence-manager/evidence-manager.types.ts

Cleaned up code, improved comments & var/fn names in evidence-select & related components. Also removed the type adornments on assertion-submit's form config objects, as those aren't working as intended and are causing more problems than they solve. To work properly & preserve types in form config arrays, field type config & options will need proper discriminated union/intersection types, similar to the [column preference options](https://github.com/griffithlab/civic-v2/blob/3564afaf9f13ad553f1abfdd7fe8a0c0ce3588e0/client/src/app/forms2/types/evidence-select/evidence-manager/evidence-manager.types.ts#L169) in evidence-manager.types used to type its [table options array](https://github.com/griffithlab/civic-v2/blob/3564afaf9f13ad553f1abfdd7fe8a0c0ce3588e0/client/src/app/forms2/types/evidenc …

forms-2 <-- evidence-select post merge improvements

---

client/src/app/forms2/types/evidence-select/evidence-manager/evidence-manager.component.html
client/src/app/forms2/types/variant-select/variant-manager/variant-manager.component.html
client/src/app/forms2/types/variant-select/variant-manager/variant-manager.component.less
client/src/app/forms2/types/variant-select/variant-manager/variant-manager.config.ts
client/src/app/forms2/types/variant-select/variant-manager/variant-manager.types.ts
client/src/app/forms2/types/variant-select/variant-select.type.ts

The col still needs an overflow counter and popover to display the omitted aliases - currently overflow is handled with CSS ellipsis. At least users can now filter by alias, bringing the table mostly up to par w/ the current variant table in select mode.

adds aliases col to variant-select's manager table

---

client/src/app/forms2/components/entity-select/entity-select.component.html
client/src/app/forms2/types/disease-select/disease-select.type.html
client/src/app/forms2/types/disease-select/disease-select.type.less
client/src/app/forms2/types/gene-select/gene-select.type.html
client/src/app/forms2/types/therapy-select/therapy-select.type.html
client/src/app/forms2/types/variant-select/variant-select.type.html

This prevents them from unsightly resizing/repositioining to display options w/ many aliases. Overflow text like aliases now provide a tooltip to view all the option contents.
Closes #789

entity-select dropdowns now limited to select width

---

client/src/app/forms2/types/molecular-profile-select/molecular-profile-select.type.html

Updates the molecular-profile-select field with several UX improvements.
This initial commit includes a workaround for the dropdown menu appearing if a selected tag's background is clicked. It's not quite a fix b/c it does not prevent a click on the select area's background from displaying a dropdown. However, it swiches the select's display mode to inline, causing it to wrap more tightly around the tag, thus reducing the changes a user will click the background instead of the tag's close btn. An actual fix would require switching out the select for a simple tag display, which I wanted to avoid in order to faciliate a single and muli mp mode using the same component as we do with other fields.

molecular-profile select field UX improvements

---

server/Gemfile.lock

These changes in Gemfile.lock were added by bundler. If they can be merged w/o breaking the server on other platforms it would be helpful, since I have been reverting these whenever they occur in order to keep them out of client-side commits.

platform & gem updates for arm64 architecture

---

client/src/app/core/utilities/molecular-profile-parser.ts
client/src/app/forms2/components/entity-tag/entity-tag.component.less
client/src/app/forms2/types/molecular-profile-select/molecular-profile-select.module.ts
client/src/app/forms2/types/molecular-profile-select/molecular-profile-select.type.html
client/src/app/forms2/types/molecular-profile-select/molecular-profile-select.type.less
client/src/app/forms2/types/molecular-profile-select/molecular-profile-select.type.ts
client/src/app/forms2/types/molecular-profile-select/mp-expression-editor/mp-editor-popover-help.component.html
client/src/app/forms2/types/molecular-profile-select/mp-expression-editor/mp-editor-popover-help.component.ts
client/src/app/forms2/types/molecular-profile-select/mp-expression-editor/mp-expression-editor.component.html
client/src/app/forms2/types/molecular-profile-select/mp-expression-editor/mp-expression-editor.component.less
client/src/app/forms2/types/molecular-profile-select/mp-expression-editor/mp-expression-editor.component.ts
client/src/app/forms2/types/variant-select/variant-select.type.html
client/src/app/forms2/types/variant-select/variant-select.type.ts

Fixes a number of layout, style, and display logic issues/annoyances:
- improved layout of expression editor by reducing the number of UI elements, text
-- all error editor messages (errors, actions, buttons) moved out of the editor and/or preview window into alert components
-- errors shortened into message and 'help' components, help text available via tooltip in alert
-- removed editor/preview component labels
-- moved Append VID form into a button popover
- improved interaction of the parent mp-select and editor w/ improved messages & display logic
-- mp-select's tag or gene/variant form replaced w/ 'Select MP...' message if Editor is open
-- editor messages & button display 'Select' or 'Add' messaging/actions depending on MP's existence
**IMPROVED LAYOUT**
**IMPROVED ERROR MESSAGES** …

mp-select field UX improvements

---

server/app/graphql/types/queries/typeahead_queries.rb

In cases where we match the query first on some criteria and then on additional criteria if we didn't get enough results, make sure that results from the first query do not appear in the second.

Do not return duplicate typeahead suggestions

---

client/src/app/components/layout/auth-options-list/auth-options-list.component.html
client/src/app/components/layout/auth-options-list/auth-options-list.component.less
client/src/app/views/users/users-detail/users-detail.component.html
client/src/app/views/users/users-detail/users-detail.component.less
client/src/assets/images/orcid-logo.svg

The ORCID brand guidelines say not to use their logo smaller than 16x16 pixels and our other provider icons were 14x14 so I bumped them up to 16 so they'd all be the same size...
closes #371

add orcid logo to oauth login option

---

client/src/app/forms2/components/org-selector-btn-group/org-selector-btn-group.component.ts
client/src/app/forms2/components/tables/table-counts/table-counts.component.ts
client/src/app/forms2/mixins/base/base-field.ts
client/src/app/forms2/types/evidence-select/evidence-manager/evidence-manager.component.html
client/src/app/forms2/types/variant-select/variant-manager/enum-filter-menu/enum-filter-menu.component.less
client/src/app/forms2/types/variant-select/variant-manager/enum-filter-menu/enum-filter-menu.component.ts
client/src/app/forms2/types/variant-select/variant-manager/table-filter-input/table-filter-input.component.ts
client/src/app/forms2/types/variant-select/variant-manager/variant-manager.component.html

A few of these were identical selectors which were easily fixed with renaming. Most of the warnings were produced by the `base-field` mixin that all of the new form components use. All of those fields are compiling themselves using that same base class, and since it does not define a selector, NG gives it a default of 'ng-component'. The selector defined in the parent component's options does not override the base's selector, since those are set at compile-time (hence the requirement that selectors be strings and not variables or functions).
The solution turned out to be simple, replacing base-field's `@Component` decorator with `@Injectable`, which allows the use of `@UntilDestroy` within base-field and does not kick off NG's component compilation w/ its component collision testing. Now, …

fixed NG0912 selector collision warnings

---

server/app/models/actions/suggest_revision_set.rb
server/app/models/concerns/moderated.rb
server/app/models/molecular_profile.rb
server/app/models/variant.rb

Previously we had added a unique validation for MP and Variant names. Unfortunately, this broke validation when proposing revisions, as the way we validate those is to `new` up a copy with the revisions applied and run the validations.
This would always result in a duplicate name failure, so we had to back off the validation for that case as a temporary fix.
This introduces a more permanent fix. All `Moderated` entities now have an `in_revision_validation_context`. This will be set to `true` when the object is the result of a revision proposal and validations can take that into account in their logic.
As a result, the name validation can function appropriately.
closes #863

Validate name uniqueness, but be aware of revision context

---

client/src/app/forms/molecular-profile-revise/molecular-profile-revise.queries.gql
client/src/app/forms2/config/molecular-profile-revise/molecular-profile-revise.form.html
client/src/app/forms2/config/molecular-profile-revise/molecular-profile-revise.form.ts
client/src/app/forms2/config/molecular-profile-revise/molecular-profile-revise.query.gql
client/src/app/forms2/types/tag-input/tag-input.type.html
client/src/app/forms2/types/tag-input/tag-input.type.ts
client/src/app/generated/civic.apollo-helpers.ts
client/src/app/generated/civic.apollo.ts
client/src/app/generated/server.model.graphql
client/src/app/generated/server.schema.json
server/app/graphql/types/entities/molecular_profile_type.rb
server/app/models/actions/suggest_molecular_profile_revision.rb
server/app/models/variant.rb
server/misc_scripts/liftover_variant_aliases.rb

* backfill script to perform initial sync
* MP edit form disables Aliases when editing a Simple MP
* When variant revisions are accepted, set the corresponding single variant MP's aliases to the variant's aliases
* Don't allow alias revisions to be created on the backend for simple MPs
closes #866

Make Simple MPs inherit aliases from their Variant

---

client/src/app/forms2/config/evidence-submit/evidence-submit.form.html
client/src/app/forms2/config/evidence-submit/evidence-submit.form.ts
client/src/app/forms2/types/direction-select/direction-select.type.ts
client/src/app/forms2/types/significance-select/significance-select.type.ts
client/src/app/views/evidence/evidence-detail/evidence-detail.module.ts
client/src/app/views/evidence/evidence-detail/evidence-detail.view.html
server/app/models/input_adaptors/evidence_item_input_adaptor.rb

Evidence Pages have a "Clone this EID" button, which will take the user to the Evidence Submit page with all the fields pre-filled, minus the description.
Additional checks have been added to ensure an identical EID cannot be submitted.

Allow creation of new EIDs based on existing EIDs

---

client/src/app/forms/variant-submit/variant-submit.form.html
client/src/app/forms/variant-submit/variant-submit.form.less
client/src/app/forms/variant-submit/variant-submit.form.ts
client/src/app/forms/variant-submit/variant-submit.module.ts

This updates the variant-submit form to use forms2 fields, with variant-select's built-in quick-add form for creating new variants. The form behaves similarly to the mp-select field, providing gene and variant fields. After a new variant is created, a success message is display, containing a link to the new variant's summary page.

hotfix for variant-submit form

---

client/src/app/views/welcome/welcome.component.ts

Removed '(HTML)' string from headline.

fix welcome page news item text

---

server/app/jobs/set_allele_registry_id_single_variant.rb
server/app/jobs/set_allele_registry_ids.rb
server/app/jobs/update_allele_registry_ids.rb

E.g., the coordinates for https://civicdb.org/variants/437/revisions were updated to a categorical variant (removing the ref and var alleles) so there is no longer an applicable allele registry entry. The current logic wasn't able to reset the allele registry id.

Set allele_registry_id to None if the coordinates no longer resolve

---

client/src/app/components/variants/my-variant-info/my-variant-info.component.html

COSMIC updated their identifiers and COSM identifiers are now considered "legacy". Linkouts still work when the COSM prefixed is removed from the legacy ID.

Fix COSMIC linkouts

---

server/app/graphql/mutations/suggest_evidence_item_revision.rb
server/app/models/input_adaptors/evidence_item_input_adaptor.rb

When revising only the description of an EID the current logic returns the revised EID as a duplicate because we're checking all fields except for description, which are still identical. This updated logic explicitly removes the revised EID from the duplication check.

Exclude EID to be revised from duplication check

---

client/src/app/forms/config/assertion-revise/assertion-revise.query.gql
client/src/app/forms/config/assertion-submit/assertion-submit.query.gql
client/src/app/forms/config/evidence-revise/evidence-revise.form.ts
client/src/app/forms/config/evidence-revise/evidence-revise.query.gql
client/src/app/forms/config/evidence-submit/evidence-submit.form.ts
client/src/app/forms/config/evidence-submit/evidence-submit.query.gql
client/src/app/forms/config/variantgroup-revise/variantgroup-revise.form.ts
client/src/app/forms/config/variantgroup-revise/variantgroup-revise.query.gql
client/src/app/forms/config/variantgroup-submit/variantgroup-submit.query.gql
client/src/app/forms/types/variant-select/variant-quick-add/variant-quick-add.query.gql
client/src/app/forms/utilities/variant-group-to-model-fields.ts
client/src/app/generated/civic.apollo.ts

Copied over several gql query files had been missed in migrating those forms to the forms2 architecture, causing generate-apollo to fail, and TS compilation errors about missing, misnamed gql mutations.

restored missing forms gql files

---

server/app/admin/diseases_admin.rb
server/app/admin/events_admin.rb
server/app/admin/revisions_admin.rb
server/app/admin/therapies_admin.rb
server/app/admin/variants_admin.rb

* error messages will now correctly display next to the "deprecated" checkbox
* variant admin wasn't loading due to including removed fields
* disallow deleting most entities in the admin

Various admin fixes

---

server/app/graphql/types/queries/typeahead_queries.rb
server/app/models/therapy.rb

Fix variable name typo in therapy typeahead

---

client/src/app/forms/config/evidence-revise/evidence-revise.form.config.ts
client/src/app/forms/config/evidence-submit/evidence-submit.form.config.ts
client/src/app/forms/mixins/entity-select-field.mixin.ts
client/src/app/forms/test-pages/layout-tests/horizontal-form/horizontal-form.page.html
client/src/app/forms/test-pages/layout-tests/inline-form/inline-form.page.html
client/src/app/forms/types/direction-select/direction-select.type.ts
client/src/app/forms/types/disease-select/disease-select.type.ts
client/src/app/forms/types/interaction-select/interaction-select.type.ts
client/src/app/forms/types/level-select/level-select.type.ts
client/src/app/forms/types/molecular-profile-select/molecular-profile-select.type.ts
client/src/app/forms/types/molecular-profile-select/mp-finder/mp-finder.component.html
client/src/app/forms/types/molecular-profile-select/mp-finder/mp-finder.component.ts
client/src/app/forms/types/origin-select/origin-select.type.ts
client/src/app/forms/types/rating/rating.type.html
client/src/app/forms/types/rating/rating.type.less
client/src/app/forms/types/rating/rating.type.ts
client/src/app/forms/types/significance-select/significance-select.type.ts
client/src/app/forms/types/type-select/type-select.type.ts
client/src/app/forms/wrappers/form-field/form-field.wrapper.html
client/src/app/forms/wrappers/form-field/form-field.wrapper.less
client/src/app/forms/wrappers/form-field/form-field.wrapper.ts
client/src/app/layout/layout-routing.module.ts
client/src/themes/default.less
client/src/themes/global-variables.less

Currently the status of a form field (required, disabled, error, valid) can be difficult to discern. This PR adjusts the styling on form fields in order to better visually differentiate their status for the user.
**Initially fields will either be default, required, and/or disabled**
**As the form is populated, valid and error statuses will be displayed**

form field status display improved

---

client/src/app/generated/civic.apollo-helpers.ts
client/src/app/generated/civic.apollo.ts

After updating to the latest main branch after big merge, when I export a current schema with `rake graphql:schema:dump`, it produces a schema that causes the client apollo services to have several differences with the staging deploy.
The client build was displaying forms w/o any errors before and currently appears to be working fine with these updates. It could be that a client-side rebuild got lost in the merges, or my db got out of sync somewhere.

client apollo codegen service components have updates

---

client/src/app/forms/config/assertion-submit/assertion-submit.form.config.ts
client/src/app/forms/mixins/entity-select-field.mixin.ts

This PR fixes entity-select's initial status, which was showing as invalid on Submit forms on initial display. Now it shows the default untouched status.

entity-select fields now display proper status on init

---

client/src/app/core/pipes/icon-name-for-event-action-pipe.ts

Adds a case to `iconNameForEventFeed` pipe to handle new `ComplexMolecularProfileCreated` event type.

fix unknown icon error in event-feed

---

server/app/graphql/resolvers/variants.rb

The Variants resolver should exclude deprecated variants

---

client/src/app/forms/types/tag-input/tag-input.module.ts
client/src/app/forms/types/tag-input/tag-input.type.ts

tag shouldnt use model updating on blur when in multiselect mode
closes #987

Fix Alias form elements

---

server/app/models/frontend_router.rb

Allow the `FrontendRouter` to pass along a lambda that will be used to transform the incoming identifier. Default to no-op if not provided.
Always upcase incoming gene symbols.
closes #993

Support case insensitive gene symbols for entrez links

---

server/app/tsv_formatters/assertion_tsv_formatter.rb

The assertion linkout was being generated twice which shifted the subsequent columns incorrectly.

Remove extraneous data column on assertion tsv

---

client/src/app/forms/config/molecular-profile-revise/molecular-profile-revise.form.config.ts
client/src/app/forms/config/molecular-profile-revise/molecular-profile-revise.form.ts

The previous version was fragile and dependent on the the layout and ordering of the form config. This moves the logic to the config itself.

Fix MP alias form field enable/disable logic

---

server/Gemfile
server/Gemfile.lock
server/app/assets/config/manifest.js
server/app/controllers/graphiql_controller.rb
server/app/views/graphiql/show.html.erb
server/config/initializers/graphiql.rb
server/config/query_examples/accepted_evidence.yml
server/config/query_examples/evidence_counts.yml
server/config/query_examples/evidence_for_variant.yml
server/config/routes.rb

Examples dynamically loaded from `server/config/query_examples`
Needs a better copy of the logo and some formatting fixes before we merge.

Example Queries Wrapper around GraphiQL sandbox

---

server/app/graphql/resolvers/quicksearch.rb

The GraphQL enum will not resolve for `Variants::FactorVariant` so use `Variant` instead. `.base_class` will get the uppermost class in the inheritance hierarchy that isn't ApplicationRecord/Activerecord::Base

always use the base class in search, not the inherited type

---

client/src/app/components/variants/variants-menu/variants-menu.component.ts
client/src/app/components/variants/variants-menu/variants-menu.gql
client/src/app/generated/civic.apollo.ts

For the built in relay style pagination/merge function to work, apparently it needs to be `edges { node}` instead of `node` directly.

Fix variant menu pagination

---

server/app/reports/diseases_with_icdo.rb
server/app/reports/eids_with_onset_terms.rb
server/app/reports/reports.rb

* Add report for eids with onset terms
* Add report for counting ICDO/DOID associated eids

Add additional reports

---

client/src/app/components/assertions/assertions-table/assertions-table.component.html
client/src/app/components/evidence/evidence-table/evidence-table.component.html
client/src/app/forms/types/evidence-select/evidence-manager/evidence-manager.component.html
client/src/app/forms/types/evidence-select/evidence-manager/evidence-manager.config.ts
client/src/app/forms/types/evidence-select/evidence-manager/evidence-manager.types.ts
client/src/app/generated/civic.apollo.ts
client/src/app/generated/server.model.graphql
client/src/app/generated/server.schema.json
server/app/graphql/resolvers/top_level_assertions.rb
server/app/graphql/resolvers/top_level_evidence_items.rb
server/app/graphql/types/base_connection.rb
server/app/graphql/types/browse_tables/assertion_sort_columns.rb
server/app/graphql/types/browse_tables/evidence_sort_columns.rb

closes #1051 
This PR ensures duplicate results do not appear on browse tables as a result of joining across tables. It also disables sorting where it doesn't make sense to support it (ie: when there are multiple items)

Various browse table fixes

---

server/app/validators/deprecation_validator.rb

Check of there are any open revisions using a therapy/disease before deprecating it

---

client/src/app/components/organizations/organizations-table/organizations-table.component.html
client/src/app/components/organizations/organizations-table/organizations-table.component.ts
client/src/app/components/organizations/organizations-table/organizations-table.query.gql
client/src/app/generated/civic.apollo-helpers.ts
client/src/app/generated/civic.apollo.ts
client/src/app/generated/server.model.graphql
client/src/app/generated/server.schema.json
server/app/graphql/resolvers/top_level_organizations.rb
server/app/graphql/types/browse_tables/browse_organization_type.rb
server/app/graphql/types/browse_tables/organization_sort_columns.rb
server/app/models/materialized_views/organization_browse_table_row.rb
server/db/migrate/20240625182325_create_organization_browse_table_rows.rb
server/db/schema.rb
server/db/views/organization_browse_table_rows_v01.sql

Added a materialized view for the organizations table

---

client/src/app/generated/server.model.graphql
client/src/app/generated/server.schema.json
server/app/graphql/types/entities/molecular_profile_type.rb
server/app/models/molecular_profile.rb

Remove rejected EIDs and Assertions from MP relations by default

---

client/src/app/components/features/features-table/features-table.component.html
client/src/app/layout/layout.component.html
client/src/app/layout/layout.component.less

Fixes a couple of issues:
- features-table's fixed columns configuration which were causing issues with horizontal scrolling
- sidebar menu styles weren't hiding menu item labels when menu is collapsed

fixes minor UI issues discovered during v18 upgrades

---

client/src/app/components/activities/activity-feed/activity-feed.component.html
client/src/app/components/comments/comment-display/comment-display.component.html
client/src/app/components/comments/comment-display/comment-display.component.ts
client/src/app/components/comments/comment-display/comment-display.module.ts

Instead of a comment box with no comment, this will display secondary text indicating that a submission comment was not provided.

Improve Submission Comment display when no comment exists

---

client/src/app/components/diseases/diseases-table/diseases-table.component.html
client/src/app/components/diseases/diseases-table/diseases-table.component.ts
client/src/app/components/diseases/diseases-table/diseases-table.module.ts
client/src/app/components/diseases/diseases-table/diseases-table.query.gql
client/src/app/components/therapies/therapies-table/therapies-table.component.html
client/src/app/components/therapies/therapies-table/therapies-table.component.ts
client/src/app/components/therapies/therapies-table/therapies-table.module.ts
client/src/app/components/therapies/therapies-table/therapies-table.query.gql
client/src/app/generated/civic.apollo-helpers.ts
client/src/app/generated/civic.apollo.ts
client/src/app/generated/server.model.graphql
client/src/app/generated/server.schema.json
server/app/graphql/resolvers/browse_diseases.rb
server/app/graphql/resolvers/browse_features.rb
server/app/graphql/resolvers/browse_molecular_profiles.rb
server/app/graphql/resolvers/browse_variants.rb
server/app/graphql/resolvers/shared/search_helpers.rb
server/app/graphql/resolvers/top_level_assertions.rb
server/app/graphql/resolvers/top_level_evidence_items.rb
server/app/graphql/resolvers/top_level_therapies.rb
server/app/graphql/types/browse_tables/browse_disease_type.rb
server/app/graphql/types/browse_tables/browse_therapy_type.rb
server/app/jobs/refresh_materialized_views.rb
server/app/models/materialized_views/therapy_browse_table_row.rb
server/db/migrate/20240821202632_update_disease_browse_table_rows_to_version_8.rb
server/db/migrate/20240821202933_create_therapy_browse_table_rows.rb
server/db/schema.rb
server/db/views/disease_browse_table_rows_v08.sql
server/db/views/therapy_browse_table_rows_v01.sql

* Add aliases (and filtering) to disease and therapy browse tables
* Fix bug where supplying a therapy id AND and therapy name at the same time would result in incorrect results
* Port therapy browse to use a materialized view to account for the additional complexity
* Minor refactoring of view query helper methods
closes #1066

Disease and Therapy browse table improvements

---

client/src/app/components/molecular-profiles/molecular-profile-factor-variant-card/molecular-profile-factor-variant-card.component.html
client/src/app/components/molecular-profiles/molecular-profile-factor-variant-card/molecular-profile-factor-variant-card.component.ts
client/src/app/components/variants/factor-variant-summary/factor-variant-summary.page.html

(also clean up the duplicated ncit box on the variant summary page)
closes #1079

Add NCIt details to Factor Variant card in MP view

---

server/app/graphql/resolvers/browse_sources.rb

The ongoing issues with the ASCO API means ASCO sources are being left in stubbed state. This causes issues when they're returned in the browse views with non-nullable fields as null.
Until we can get a longer term ASCO fix in place, just filter them out of the browse view results.
fixes (the filtering bug in) #1022

Filter out sources without citations from browse view

---

client/src/app/components/assertions/assertions-table/assertions-table.component.html
client/src/app/components/assertions/assertions-table/assertions-table.component.ts
client/src/app/components/assertions/assertions-table/assertions-table.module.ts
client/src/app/components/evidence/evidence-table/evidence-table.component.html
client/src/app/components/evidence/evidence-table/evidence-table.component.ts
client/src/app/components/evidence/evidence-table/evidence-table.module.ts
client/src/app/generated/civic.apollo.ts
client/src/app/generated/server.model.graphql
client/src/app/generated/server.schema.json
server/app/graphql/resolvers/top_level_assertions.rb
server/app/graphql/resolvers/top_level_evidence_items.rb
server/app/graphql/types/evidence_status_filter_type.rb

Default to showing all non-rejected, but allow users to pick any status or "show all"
closes #1088

Allow evidence and assertion tables to be filtered by status

---

server/app/graphql/types/queries/typeahead_queries.rb
server/app/graphql/types/variants/gene_variant_type.rb
server/app/models/activities/create_variant.rb

This PR addresses the following bugs:
- Closes #1118 by commenting out any order by LENGTH statements since they cause unexplained errors on production
- Coordinate stub wasn't being added when a new gene variant was created
- Closes #1120 by fixing the promise resolution for counts

Various fusion bugfixes

---

server/app/jobs/populate_clinical_trial_record.rb
server/app/lib/scrapers/clinical_trial.rb
server/app/lib/scrapers/clinical_trial_response.rb
server/app/models/clinical_trial.rb

The API we were using in v1 no longer exists so this also updates the old jobs to use the new api.
We'll want to run a backfill in the console once deployed.

Auto update clinical trial names and descriptions

---

server/app/models/materialized_views/source_browse_table_row.rb

This is required for the join across to clinical trials via the `has_and_belongs_to_many` relation.

add explicit primary key to source browse model

---

server/app/graphql/resolvers/top_level_molecular_profiles.rb

This brings the filtering behavior into alignment between the Variant menu and MP menu on feature pages and also makes the behavior match what the documentation claims it does anyways.

add alias matching to MP name filtering

---

server/app/jobs/generate_tsvs.rb

This will remove any internal tabs or line breaks for description fields and also should ensure correct escaping of quotes in tsv exports.
closes #1157

use csv library to ensure correct quoting, squish internal whitespace

---

client/src/app/forms/components/user-profile/user-profile.form.html

closes #1158 
This now behaves as expected. If no country is set, it will display `Select a Country` and if they save their profile without doing so, it will default to null.

add default placeholder text to country select on profile page

---

.github/workflows/test_example_scripts.yml
examples/fetch_acmg_code.R
examples/fetch_all_variants.py
examples/fetch_variant_links.rb

Add script to ensure example scripts keep working

---

client/src/app/generated/civic.apollo-helpers.ts
client/src/app/generated/civic.apollo.ts
client/src/app/generated/server.model.graphql
client/src/app/generated/server.schema.json
client/src/app/views/releases/releases-main/releases-list.query.gql
client/src/app/views/releases/releases-main/releases-main.component.html
server/app/graphql/types/data_release_type.rb
server/app/graphql/types/queries/data_release_query.rb

The previous PR renames it on the backend and sets up an alias/link for backwards compatibility, this PR changes the naming on the downloads page.

Rename gene tsv to feature tsv on the downloads page

---

client/src/app/forms/config/fusion-variant-revise/fusion-variant-revise.form.config.ts
server/app/graphql/mutations/suggest_fusion_variant_revision.rb

Previously, the revise fusion variant form shared the same validation rules as the "create fusion variant" form. This meant requiring 5' or 3' coordinates to be entered (depending on the properties of the Feature).
However, when revising a representative Fusion variant that may not have coordinates specified, this would render a user unable to provide an alias or additional SO terms.
This changes the rules so that:
* Exons are required if the corresponding transcript is filled in
* Transcripts are required if the corresponding exon is filled in
* Ensembl version and Reference build are required if either transcript is filled in
* Offset and Offset direction continue to work as before

When revising a fusion variant, allow for optional exon coordinates

---

server/app/graphql/types/queries/typeahead_queries.rb

This behavior did not work on the version of Postgres we were using previously. I've verified it works on the current prod instance so we can bring it back.

rank typeahead results by length of matched name

---

server/app/lib/link_adaptors/phenotype.rb
server/app/models/frontend_router.rb

In addition to adding logic for resolving diseases, therapies, and phenotypes by doid, ncit_id, and hpo_id, respectively, this PR  also adds link resolvers for phenotypes by ID, factors and fusions by feature ID and updates some logic that was incorrectly using the feature_instance_id instead of the feature ID.
TODO:

Update short links to allow doid, ncit_id, and hpo_id

---

client/src/app/components/activities/activity-feed/feed-item/feed-item.component.html
client/src/app/forms/types/evidence-select/evidence-select.type.ts
client/src/app/views/organizations/organizations-events/organizations-events.component.html
client/src/app/views/organizations/organizations-events/organizations-events.component.ts

Updated activity feed configuration on the organizations-events page, and the show organization logic in feed-item component to synchronize the feed-settings 'Show Organization' option. Fixes #1192.
The Show Organization option wasn't working on the organization-events page due to a couple of issues. First, the activity-feed initializes with default feed settings which sets showOrganization to 'true'. These settings are only overridden by the cvcSettings input. Second, feed-item's logic overrode showOrganization with the activity-feed mode (organization, subject, user, unscoped), so the organization would never be shown if its mode was 'ORGANIZATION'. 
Adding cvcSettings configuration w/ showOrganization set to 'true', and removing the mode check from the feed item org display logic fixed …

Show Organization settings now work properly in organization activity tab

---

client/src/app/components/genes/gene-base-summary/gene-base-summary.page.html

The URL format changed again so the links were broken (again). This new format also allows us to pre-select the CIViC annotation track so this actually closes #836

Fix ProteinPaint url

---

server/app/graphql/types/queries/typeahead_queries.rb

I thought we had removed all of these previously, but looks like we missed one. The `.order` clause generates invalid SQL when we're matching on aliases.

Remove invalid order clause

---

server/app/models/activities/base.rb
server/app/models/activities/submit_assertion.rb
server/app/models/activities/submit_evidence_item.rb

This adds an optional `setup` method to activities that will be called before any other processing has completed.
In this case, it is used to run validation on EIDs and Assertions prior to the creation of the activity entity, which will trigger a save on the EID automatically.
This results in the correct error coming back from the API:
Looking through the rest of the activities, I believe these are the only two places it makes sense to do this. The only other place is maybe creating Fusions because they have some fairly elaborate validation rules too, but much of that happens in a background task.
closes #1201

Submitting EIDs and Assertions should fail early if the entities would be invalid

---

client/src/app/generated/civic.apollo.ts
client/src/app/generated/server.model.graphql
client/src/app/generated/server.schema.json
server/app/graphql/resolvers/top_level_therapies.rb

We import a large chunk of the NCIt to power the typeahead, but it can also be useful to only iterate through therapies that have associated CIViC evidence. This filter will allow for that.
Its also a prerequisite for dgidb/dgidb-v5#576

Add hasLinkedEvidence filter to therapies endpoint

---

client/src/app/app.component.html
client/src/app/app.module.ts
client/src/app/components/app/environment-banner/environment-banner.component.html
client/src/app/components/app/environment-banner/environment-banner.component.less
client/src/app/components/app/environment-banner/environment-banner.component.ts
client/src/environments/environment.prod.ts
client/src/environments/environment.ts
server/app/controllers/static_controller.rb
server/config/initializers/environment_banner.rb

When developing features, we often find ourselves having to double check the URL to make sure we're not going to perform actions on the real site. This should help that by adding a fixed banner to the top of the site when we're in dev mode.
It would be nice potentially to differentiate between staging and dev as well, but the `production` flag on the frontend doesn't handle that case at the moment, it just indicates that the frontend build is a "production" build of the angular app which is indeed what gets deployed to staging.

Add banner indicating when we are in a non-production environment

---

server/app/jobs/generate_nightly_uniprot_file.rb
server/config/scheduled_tasks.yml
server/db/migrate/20250416144840_add_uniprot_id.rb
server/db/schema.rb

This closes griffithlab/civic-client#1533.
The file currently looks like this:
The third column is based on this comment: https://github.com/griffithlab/civic-client/issues/1533#issuecomment-902187919
But I'm not sure if it needs to be formatted a specific way or need a specific header, as the initial comment also mentions xrefs. Is there more context somewhere else?
Uniprot can link using the entrez id column with the following format: `https://civicdb.org/links/entrez_id/<entrez id>` and the file will be available at `https://civicdb.org/downloads/nightly/uniprot-civic-nightly.tsv`

Add scheduled job for generating Uniprot mapping TSV

---

server/app/tsv_formatters/molecular_profile_tsv_formatter.rb
server/app/tsv_formatters/variant_tsv_formatter.rb

In response to the civic-help email and in order to prevent confusion, only include variants and MPs in the TSVs if they have at least one accepted EID or AID.

Make MP and Variant TSV queries consistent with each other

---

server/app/models/actions/suggest_revision_set.rb
server/app/models/activities/suggest_revision_set.rb

* If only duplicate revisions are proposed, raise an exception and fail
* Only add newly created revisions as linked entities, not any preexisting revisions
closes #1240

Improve handling of duplicate revisions

---

client/src/app/components/variants/variant-info/variant-info.component.html

This is a wording change that Rachel requested. The panel would look like this:

Adjust OpenCravat predictor tab heading

---

server/app/views/graphiql/show.html.erb

The new graphiql release broke the page on our site. I have fixed it by starting with the porting guide found here: https://github.com/graphql/graphiql/blob/main/docs/migration/graphiql-5.0.0.md#graphiql and then incorporating our query logic and wrapper html into their example.

update graphiql page to use new CDN system and 5.0 release

---

client/src/app/components/genes/my-gene-info/my-gene-info.component.html

The MyGeneInfo component's template was throwing errors for genes with no aliases specified in MyGeneInfo's data. This also prevented the MP/Variant/Fusion component from loading.
I also removed an extraneous, unrelated empty component file.

fixes missing my-gene-info display on some gene summaries

---

server/app/jobs/application_job.rb

This is actually the default behavior for background jobs after rails 7.2 but our app was generated on rails 6.1 and loads its default config options unless overridden specifically for background compatibility: (https://github.com/griffithlab/civic-v2/blob/main/server/config/application.rb#L24)

Do not queue jobs to Sidekiq until after the corresponding Postgres transaction has committed. 

---

server/app/graphql/resolvers/browse_molecular_profiles.rb

This fixes the duplicate entries in the MP browse table that Malachi reported in slack. Basically, what was happening is that multiple MPs had identical evidence scores. In that case the sort order isn't guaranteed, so between multiple queries, the sorting of the MPs could result in them appearing across "page breaks" where there was a run of identically scored MPs.
Now, if they have the same mp score, the tie is broken by id which will result in a consistent ordering.

Sort by id if evidence score is equivalent

---

client/src/app/forms/config/gene-revise/gene-revise.query.gql
client/src/app/forms/utilities/gene-to-model-fields.ts
client/src/app/generated/civic.apollo.ts

This fixes the issue Malachi reported in slack where the description revision would apply successfully, but then not appear in the form during subsequent revision attempts.

Use feature instance description when revising gene features
